package com.example.mbgexample.domain.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.Arrays;

/**
 * Database Table Remarks:
 *   主キーなし、BLOB含む
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table nokey_with_blob
 */
public class NokeyWithBlob implements Serializable {
    /**
     * Database Column Remarks:
     *   smallint
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nokey_with_blob.field1
     *
     * @mbg.generated
     */
    private Short field1;

    /**
     * Database Column Remarks:
     *   integer
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nokey_with_blob.field2
     *
     * @mbg.generated
     */
    private Integer field2;

    /**
     * Database Column Remarks:
     *   bigint
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nokey_with_blob.field3
     *
     * @mbg.generated
     */
    private Long field3;

    /**
     * Database Column Remarks:
     *   decimal(10,3)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nokey_with_blob.field4
     *
     * @mbg.generated
     */
    private BigDecimal field4;

    /**
     * Database Column Remarks:
     *   numeric
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nokey_with_blob.field5
     *
     * @mbg.generated
     */
    private Short field5;

    /**
     * Database Column Remarks:
     *   numeric(11)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nokey_with_blob.field6
     *
     * @mbg.generated
     */
    private Long field6;

    /**
     * Database Column Remarks:
     *   numeric(11,4)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nokey_with_blob.field7
     *
     * @mbg.generated
     */
    private BigDecimal field7;

    /**
     * Database Column Remarks:
     *   smallserial
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nokey_with_blob.field8
     *
     * @mbg.generated
     */
    private Short field8;

    /**
     * Database Column Remarks:
     *   serial
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nokey_with_blob.field9
     *
     * @mbg.generated
     */
    private Integer field9;

    /**
     * Database Column Remarks:
     *   bigserial
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nokey_with_blob.field10
     *
     * @mbg.generated
     */
    private Long field10;

    /**
     * Database Column Remarks:
     *   money
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nokey_with_blob.field11
     *
     * @mbg.generated
     */
    private Double field11;

    /**
     * Database Column Remarks:
     *   varchar(100)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nokey_with_blob.field12
     *
     * @mbg.generated
     */
    private String field12;

    /**
     * Database Column Remarks:
     *   char(10)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nokey_with_blob.field13
     *
     * @mbg.generated
     */
    private String field13;

    /**
     * Database Column Remarks:
     *   text
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nokey_with_blob.field14
     *
     * @mbg.generated
     */
    private String field14;

    /**
     * Database Column Remarks:
     *   timestamp
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nokey_with_blob.field16
     *
     * @mbg.generated
     */
    private LocalDateTime field16;

    /**
     * Database Column Remarks:
     *   timestamp with time zone
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nokey_with_blob.field17
     *
     * @mbg.generated
     */
    private LocalDateTime field17;

    /**
     * Database Column Remarks:
     *   time
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nokey_with_blob.field18
     *
     * @mbg.generated
     */
    private LocalTime field18;

    /**
     * Database Column Remarks:
     *   time with time zone
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nokey_with_blob.field19
     *
     * @mbg.generated
     */
    private LocalTime field19;

    /**
     * Database Column Remarks:
     *   date
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nokey_with_blob.field20
     *
     * @mbg.generated
     */
    private LocalDate field20;

    /**
     * Database Column Remarks:
     *   interval
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nokey_with_blob.field21
     *
     * @mbg.generated
     */
    private Object field21;

    /**
     * Database Column Remarks:
     *   boolean
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nokey_with_blob.field22
     *
     * @mbg.generated
     */
    private Boolean field22;

    /**
     * Database Column Remarks:
     *   uuid
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nokey_with_blob.field23
     *
     * @mbg.generated
     */
    private Object field23;

    /**
     * Database Column Remarks:
     *   bytea
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nokey_with_blob.field15
     *
     * @mbg.generated
     */
    private byte[] field15;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table nokey_with_blob
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nokey_with_blob.field1
     *
     * @return the value of nokey_with_blob.field1
     *
     * @mbg.generated
     */
    public Short getField1() {
        return field1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nokey_with_blob.field1
     *
     * @param field1 the value for nokey_with_blob.field1
     *
     * @mbg.generated
     */
    public void setField1(Short field1) {
        this.field1 = field1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nokey_with_blob.field2
     *
     * @return the value of nokey_with_blob.field2
     *
     * @mbg.generated
     */
    public Integer getField2() {
        return field2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nokey_with_blob.field2
     *
     * @param field2 the value for nokey_with_blob.field2
     *
     * @mbg.generated
     */
    public void setField2(Integer field2) {
        this.field2 = field2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nokey_with_blob.field3
     *
     * @return the value of nokey_with_blob.field3
     *
     * @mbg.generated
     */
    public Long getField3() {
        return field3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nokey_with_blob.field3
     *
     * @param field3 the value for nokey_with_blob.field3
     *
     * @mbg.generated
     */
    public void setField3(Long field3) {
        this.field3 = field3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nokey_with_blob.field4
     *
     * @return the value of nokey_with_blob.field4
     *
     * @mbg.generated
     */
    public BigDecimal getField4() {
        return field4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nokey_with_blob.field4
     *
     * @param field4 the value for nokey_with_blob.field4
     *
     * @mbg.generated
     */
    public void setField4(BigDecimal field4) {
        this.field4 = field4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nokey_with_blob.field5
     *
     * @return the value of nokey_with_blob.field5
     *
     * @mbg.generated
     */
    public Short getField5() {
        return field5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nokey_with_blob.field5
     *
     * @param field5 the value for nokey_with_blob.field5
     *
     * @mbg.generated
     */
    public void setField5(Short field5) {
        this.field5 = field5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nokey_with_blob.field6
     *
     * @return the value of nokey_with_blob.field6
     *
     * @mbg.generated
     */
    public Long getField6() {
        return field6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nokey_with_blob.field6
     *
     * @param field6 the value for nokey_with_blob.field6
     *
     * @mbg.generated
     */
    public void setField6(Long field6) {
        this.field6 = field6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nokey_with_blob.field7
     *
     * @return the value of nokey_with_blob.field7
     *
     * @mbg.generated
     */
    public BigDecimal getField7() {
        return field7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nokey_with_blob.field7
     *
     * @param field7 the value for nokey_with_blob.field7
     *
     * @mbg.generated
     */
    public void setField7(BigDecimal field7) {
        this.field7 = field7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nokey_with_blob.field8
     *
     * @return the value of nokey_with_blob.field8
     *
     * @mbg.generated
     */
    public Short getField8() {
        return field8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nokey_with_blob.field8
     *
     * @param field8 the value for nokey_with_blob.field8
     *
     * @mbg.generated
     */
    public void setField8(Short field8) {
        this.field8 = field8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nokey_with_blob.field9
     *
     * @return the value of nokey_with_blob.field9
     *
     * @mbg.generated
     */
    public Integer getField9() {
        return field9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nokey_with_blob.field9
     *
     * @param field9 the value for nokey_with_blob.field9
     *
     * @mbg.generated
     */
    public void setField9(Integer field9) {
        this.field9 = field9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nokey_with_blob.field10
     *
     * @return the value of nokey_with_blob.field10
     *
     * @mbg.generated
     */
    public Long getField10() {
        return field10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nokey_with_blob.field10
     *
     * @param field10 the value for nokey_with_blob.field10
     *
     * @mbg.generated
     */
    public void setField10(Long field10) {
        this.field10 = field10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nokey_with_blob.field11
     *
     * @return the value of nokey_with_blob.field11
     *
     * @mbg.generated
     */
    public Double getField11() {
        return field11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nokey_with_blob.field11
     *
     * @param field11 the value for nokey_with_blob.field11
     *
     * @mbg.generated
     */
    public void setField11(Double field11) {
        this.field11 = field11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nokey_with_blob.field12
     *
     * @return the value of nokey_with_blob.field12
     *
     * @mbg.generated
     */
    public String getField12() {
        return field12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nokey_with_blob.field12
     *
     * @param field12 the value for nokey_with_blob.field12
     *
     * @mbg.generated
     */
    public void setField12(String field12) {
        this.field12 = field12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nokey_with_blob.field13
     *
     * @return the value of nokey_with_blob.field13
     *
     * @mbg.generated
     */
    public String getField13() {
        return field13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nokey_with_blob.field13
     *
     * @param field13 the value for nokey_with_blob.field13
     *
     * @mbg.generated
     */
    public void setField13(String field13) {
        this.field13 = field13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nokey_with_blob.field14
     *
     * @return the value of nokey_with_blob.field14
     *
     * @mbg.generated
     */
    public String getField14() {
        return field14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nokey_with_blob.field14
     *
     * @param field14 the value for nokey_with_blob.field14
     *
     * @mbg.generated
     */
    public void setField14(String field14) {
        this.field14 = field14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nokey_with_blob.field16
     *
     * @return the value of nokey_with_blob.field16
     *
     * @mbg.generated
     */
    public LocalDateTime getField16() {
        return field16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nokey_with_blob.field16
     *
     * @param field16 the value for nokey_with_blob.field16
     *
     * @mbg.generated
     */
    public void setField16(LocalDateTime field16) {
        this.field16 = field16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nokey_with_blob.field17
     *
     * @return the value of nokey_with_blob.field17
     *
     * @mbg.generated
     */
    public LocalDateTime getField17() {
        return field17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nokey_with_blob.field17
     *
     * @param field17 the value for nokey_with_blob.field17
     *
     * @mbg.generated
     */
    public void setField17(LocalDateTime field17) {
        this.field17 = field17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nokey_with_blob.field18
     *
     * @return the value of nokey_with_blob.field18
     *
     * @mbg.generated
     */
    public LocalTime getField18() {
        return field18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nokey_with_blob.field18
     *
     * @param field18 the value for nokey_with_blob.field18
     *
     * @mbg.generated
     */
    public void setField18(LocalTime field18) {
        this.field18 = field18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nokey_with_blob.field19
     *
     * @return the value of nokey_with_blob.field19
     *
     * @mbg.generated
     */
    public LocalTime getField19() {
        return field19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nokey_with_blob.field19
     *
     * @param field19 the value for nokey_with_blob.field19
     *
     * @mbg.generated
     */
    public void setField19(LocalTime field19) {
        this.field19 = field19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nokey_with_blob.field20
     *
     * @return the value of nokey_with_blob.field20
     *
     * @mbg.generated
     */
    public LocalDate getField20() {
        return field20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nokey_with_blob.field20
     *
     * @param field20 the value for nokey_with_blob.field20
     *
     * @mbg.generated
     */
    public void setField20(LocalDate field20) {
        this.field20 = field20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nokey_with_blob.field21
     *
     * @return the value of nokey_with_blob.field21
     *
     * @mbg.generated
     */
    public Object getField21() {
        return field21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nokey_with_blob.field21
     *
     * @param field21 the value for nokey_with_blob.field21
     *
     * @mbg.generated
     */
    public void setField21(Object field21) {
        this.field21 = field21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nokey_with_blob.field22
     *
     * @return the value of nokey_with_blob.field22
     *
     * @mbg.generated
     */
    public Boolean getField22() {
        return field22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nokey_with_blob.field22
     *
     * @param field22 the value for nokey_with_blob.field22
     *
     * @mbg.generated
     */
    public void setField22(Boolean field22) {
        this.field22 = field22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nokey_with_blob.field23
     *
     * @return the value of nokey_with_blob.field23
     *
     * @mbg.generated
     */
    public Object getField23() {
        return field23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nokey_with_blob.field23
     *
     * @param field23 the value for nokey_with_blob.field23
     *
     * @mbg.generated
     */
    public void setField23(Object field23) {
        this.field23 = field23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nokey_with_blob.field15
     *
     * @return the value of nokey_with_blob.field15
     *
     * @mbg.generated
     */
    public byte[] getField15() {
        return field15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nokey_with_blob.field15
     *
     * @param field15 the value for nokey_with_blob.field15
     *
     * @mbg.generated
     */
    public void setField15(byte[] field15) {
        this.field15 = field15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nokey_with_blob
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        NokeyWithBlob other = (NokeyWithBlob) that;
        return (this.getField1() == null ? other.getField1() == null : this.getField1().equals(other.getField1()))
            && (this.getField2() == null ? other.getField2() == null : this.getField2().equals(other.getField2()))
            && (this.getField3() == null ? other.getField3() == null : this.getField3().equals(other.getField3()))
            && (this.getField4() == null ? other.getField4() == null : this.getField4().equals(other.getField4()))
            && (this.getField5() == null ? other.getField5() == null : this.getField5().equals(other.getField5()))
            && (this.getField6() == null ? other.getField6() == null : this.getField6().equals(other.getField6()))
            && (this.getField7() == null ? other.getField7() == null : this.getField7().equals(other.getField7()))
            && (this.getField8() == null ? other.getField8() == null : this.getField8().equals(other.getField8()))
            && (this.getField9() == null ? other.getField9() == null : this.getField9().equals(other.getField9()))
            && (this.getField10() == null ? other.getField10() == null : this.getField10().equals(other.getField10()))
            && (this.getField11() == null ? other.getField11() == null : this.getField11().equals(other.getField11()))
            && (this.getField12() == null ? other.getField12() == null : this.getField12().equals(other.getField12()))
            && (this.getField13() == null ? other.getField13() == null : this.getField13().equals(other.getField13()))
            && (this.getField14() == null ? other.getField14() == null : this.getField14().equals(other.getField14()))
            && (this.getField16() == null ? other.getField16() == null : this.getField16().equals(other.getField16()))
            && (this.getField17() == null ? other.getField17() == null : this.getField17().equals(other.getField17()))
            && (this.getField18() == null ? other.getField18() == null : this.getField18().equals(other.getField18()))
            && (this.getField19() == null ? other.getField19() == null : this.getField19().equals(other.getField19()))
            && (this.getField20() == null ? other.getField20() == null : this.getField20().equals(other.getField20()))
            && (this.getField21() == null ? other.getField21() == null : this.getField21().equals(other.getField21()))
            && (this.getField22() == null ? other.getField22() == null : this.getField22().equals(other.getField22()))
            && (this.getField23() == null ? other.getField23() == null : this.getField23().equals(other.getField23()))
            && (Arrays.equals(this.getField15(), other.getField15()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nokey_with_blob
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getField1() == null) ? 0 : getField1().hashCode());
        result = prime * result + ((getField2() == null) ? 0 : getField2().hashCode());
        result = prime * result + ((getField3() == null) ? 0 : getField3().hashCode());
        result = prime * result + ((getField4() == null) ? 0 : getField4().hashCode());
        result = prime * result + ((getField5() == null) ? 0 : getField5().hashCode());
        result = prime * result + ((getField6() == null) ? 0 : getField6().hashCode());
        result = prime * result + ((getField7() == null) ? 0 : getField7().hashCode());
        result = prime * result + ((getField8() == null) ? 0 : getField8().hashCode());
        result = prime * result + ((getField9() == null) ? 0 : getField9().hashCode());
        result = prime * result + ((getField10() == null) ? 0 : getField10().hashCode());
        result = prime * result + ((getField11() == null) ? 0 : getField11().hashCode());
        result = prime * result + ((getField12() == null) ? 0 : getField12().hashCode());
        result = prime * result + ((getField13() == null) ? 0 : getField13().hashCode());
        result = prime * result + ((getField14() == null) ? 0 : getField14().hashCode());
        result = prime * result + ((getField16() == null) ? 0 : getField16().hashCode());
        result = prime * result + ((getField17() == null) ? 0 : getField17().hashCode());
        result = prime * result + ((getField18() == null) ? 0 : getField18().hashCode());
        result = prime * result + ((getField19() == null) ? 0 : getField19().hashCode());
        result = prime * result + ((getField20() == null) ? 0 : getField20().hashCode());
        result = prime * result + ((getField21() == null) ? 0 : getField21().hashCode());
        result = prime * result + ((getField22() == null) ? 0 : getField22().hashCode());
        result = prime * result + ((getField23() == null) ? 0 : getField23().hashCode());
        result = prime * result + (Arrays.hashCode(getField15()));
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nokey_with_blob
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", field1=").append(field1);
        sb.append(", field2=").append(field2);
        sb.append(", field3=").append(field3);
        sb.append(", field4=").append(field4);
        sb.append(", field5=").append(field5);
        sb.append(", field6=").append(field6);
        sb.append(", field7=").append(field7);
        sb.append(", field8=").append(field8);
        sb.append(", field9=").append(field9);
        sb.append(", field10=").append(field10);
        sb.append(", field11=").append(field11);
        sb.append(", field12=").append(field12);
        sb.append(", field13=").append(field13);
        sb.append(", field14=").append(field14);
        sb.append(", field16=").append(field16);
        sb.append(", field17=").append(field17);
        sb.append(", field18=").append(field18);
        sb.append(", field19=").append(field19);
        sb.append(", field20=").append(field20);
        sb.append(", field21=").append(field21);
        sb.append(", field22=").append(field22);
        sb.append(", field23=").append(field23);
        sb.append(", field15=").append(field15);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}