package com.example.mbgexample.domain.model;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.List;

public class NokeyWithBlobExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table nokey_with_blob
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table nokey_with_blob
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table nokey_with_blob
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nokey_with_blob
     *
     * @mbg.generated
     */
    public NokeyWithBlobExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nokey_with_blob
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nokey_with_blob
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nokey_with_blob
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nokey_with_blob
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nokey_with_blob
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nokey_with_blob
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nokey_with_blob
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nokey_with_blob
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nokey_with_blob
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nokey_with_blob
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table nokey_with_blob
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andField1IsNull() {
            addCriterion("field1 is null");
            return (Criteria) this;
        }

        public Criteria andField1IsNotNull() {
            addCriterion("field1 is not null");
            return (Criteria) this;
        }

        public Criteria andField1EqualTo(Short value) {
            addCriterion("field1 =", value, "field1");
            return (Criteria) this;
        }

        public Criteria andField1NotEqualTo(Short value) {
            addCriterion("field1 <>", value, "field1");
            return (Criteria) this;
        }

        public Criteria andField1GreaterThan(Short value) {
            addCriterion("field1 >", value, "field1");
            return (Criteria) this;
        }

        public Criteria andField1GreaterThanOrEqualTo(Short value) {
            addCriterion("field1 >=", value, "field1");
            return (Criteria) this;
        }

        public Criteria andField1LessThan(Short value) {
            addCriterion("field1 <", value, "field1");
            return (Criteria) this;
        }

        public Criteria andField1LessThanOrEqualTo(Short value) {
            addCriterion("field1 <=", value, "field1");
            return (Criteria) this;
        }

        public Criteria andField1In(List<Short> values) {
            addCriterion("field1 in", values, "field1");
            return (Criteria) this;
        }

        public Criteria andField1NotIn(List<Short> values) {
            addCriterion("field1 not in", values, "field1");
            return (Criteria) this;
        }

        public Criteria andField1Between(Short value1, Short value2) {
            addCriterion("field1 between", value1, value2, "field1");
            return (Criteria) this;
        }

        public Criteria andField1NotBetween(Short value1, Short value2) {
            addCriterion("field1 not between", value1, value2, "field1");
            return (Criteria) this;
        }

        public Criteria andField2IsNull() {
            addCriterion("field2 is null");
            return (Criteria) this;
        }

        public Criteria andField2IsNotNull() {
            addCriterion("field2 is not null");
            return (Criteria) this;
        }

        public Criteria andField2EqualTo(Integer value) {
            addCriterion("field2 =", value, "field2");
            return (Criteria) this;
        }

        public Criteria andField2NotEqualTo(Integer value) {
            addCriterion("field2 <>", value, "field2");
            return (Criteria) this;
        }

        public Criteria andField2GreaterThan(Integer value) {
            addCriterion("field2 >", value, "field2");
            return (Criteria) this;
        }

        public Criteria andField2GreaterThanOrEqualTo(Integer value) {
            addCriterion("field2 >=", value, "field2");
            return (Criteria) this;
        }

        public Criteria andField2LessThan(Integer value) {
            addCriterion("field2 <", value, "field2");
            return (Criteria) this;
        }

        public Criteria andField2LessThanOrEqualTo(Integer value) {
            addCriterion("field2 <=", value, "field2");
            return (Criteria) this;
        }

        public Criteria andField2In(List<Integer> values) {
            addCriterion("field2 in", values, "field2");
            return (Criteria) this;
        }

        public Criteria andField2NotIn(List<Integer> values) {
            addCriterion("field2 not in", values, "field2");
            return (Criteria) this;
        }

        public Criteria andField2Between(Integer value1, Integer value2) {
            addCriterion("field2 between", value1, value2, "field2");
            return (Criteria) this;
        }

        public Criteria andField2NotBetween(Integer value1, Integer value2) {
            addCriterion("field2 not between", value1, value2, "field2");
            return (Criteria) this;
        }

        public Criteria andField3IsNull() {
            addCriterion("field3 is null");
            return (Criteria) this;
        }

        public Criteria andField3IsNotNull() {
            addCriterion("field3 is not null");
            return (Criteria) this;
        }

        public Criteria andField3EqualTo(Long value) {
            addCriterion("field3 =", value, "field3");
            return (Criteria) this;
        }

        public Criteria andField3NotEqualTo(Long value) {
            addCriterion("field3 <>", value, "field3");
            return (Criteria) this;
        }

        public Criteria andField3GreaterThan(Long value) {
            addCriterion("field3 >", value, "field3");
            return (Criteria) this;
        }

        public Criteria andField3GreaterThanOrEqualTo(Long value) {
            addCriterion("field3 >=", value, "field3");
            return (Criteria) this;
        }

        public Criteria andField3LessThan(Long value) {
            addCriterion("field3 <", value, "field3");
            return (Criteria) this;
        }

        public Criteria andField3LessThanOrEqualTo(Long value) {
            addCriterion("field3 <=", value, "field3");
            return (Criteria) this;
        }

        public Criteria andField3In(List<Long> values) {
            addCriterion("field3 in", values, "field3");
            return (Criteria) this;
        }

        public Criteria andField3NotIn(List<Long> values) {
            addCriterion("field3 not in", values, "field3");
            return (Criteria) this;
        }

        public Criteria andField3Between(Long value1, Long value2) {
            addCriterion("field3 between", value1, value2, "field3");
            return (Criteria) this;
        }

        public Criteria andField3NotBetween(Long value1, Long value2) {
            addCriterion("field3 not between", value1, value2, "field3");
            return (Criteria) this;
        }

        public Criteria andField4IsNull() {
            addCriterion("field4 is null");
            return (Criteria) this;
        }

        public Criteria andField4IsNotNull() {
            addCriterion("field4 is not null");
            return (Criteria) this;
        }

        public Criteria andField4EqualTo(BigDecimal value) {
            addCriterion("field4 =", value, "field4");
            return (Criteria) this;
        }

        public Criteria andField4NotEqualTo(BigDecimal value) {
            addCriterion("field4 <>", value, "field4");
            return (Criteria) this;
        }

        public Criteria andField4GreaterThan(BigDecimal value) {
            addCriterion("field4 >", value, "field4");
            return (Criteria) this;
        }

        public Criteria andField4GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("field4 >=", value, "field4");
            return (Criteria) this;
        }

        public Criteria andField4LessThan(BigDecimal value) {
            addCriterion("field4 <", value, "field4");
            return (Criteria) this;
        }

        public Criteria andField4LessThanOrEqualTo(BigDecimal value) {
            addCriterion("field4 <=", value, "field4");
            return (Criteria) this;
        }

        public Criteria andField4In(List<BigDecimal> values) {
            addCriterion("field4 in", values, "field4");
            return (Criteria) this;
        }

        public Criteria andField4NotIn(List<BigDecimal> values) {
            addCriterion("field4 not in", values, "field4");
            return (Criteria) this;
        }

        public Criteria andField4Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("field4 between", value1, value2, "field4");
            return (Criteria) this;
        }

        public Criteria andField4NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("field4 not between", value1, value2, "field4");
            return (Criteria) this;
        }

        public Criteria andField5IsNull() {
            addCriterion("field5 is null");
            return (Criteria) this;
        }

        public Criteria andField5IsNotNull() {
            addCriterion("field5 is not null");
            return (Criteria) this;
        }

        public Criteria andField5EqualTo(Short value) {
            addCriterion("field5 =", value, "field5");
            return (Criteria) this;
        }

        public Criteria andField5NotEqualTo(Short value) {
            addCriterion("field5 <>", value, "field5");
            return (Criteria) this;
        }

        public Criteria andField5GreaterThan(Short value) {
            addCriterion("field5 >", value, "field5");
            return (Criteria) this;
        }

        public Criteria andField5GreaterThanOrEqualTo(Short value) {
            addCriterion("field5 >=", value, "field5");
            return (Criteria) this;
        }

        public Criteria andField5LessThan(Short value) {
            addCriterion("field5 <", value, "field5");
            return (Criteria) this;
        }

        public Criteria andField5LessThanOrEqualTo(Short value) {
            addCriterion("field5 <=", value, "field5");
            return (Criteria) this;
        }

        public Criteria andField5In(List<Short> values) {
            addCriterion("field5 in", values, "field5");
            return (Criteria) this;
        }

        public Criteria andField5NotIn(List<Short> values) {
            addCriterion("field5 not in", values, "field5");
            return (Criteria) this;
        }

        public Criteria andField5Between(Short value1, Short value2) {
            addCriterion("field5 between", value1, value2, "field5");
            return (Criteria) this;
        }

        public Criteria andField5NotBetween(Short value1, Short value2) {
            addCriterion("field5 not between", value1, value2, "field5");
            return (Criteria) this;
        }

        public Criteria andField6IsNull() {
            addCriterion("field6 is null");
            return (Criteria) this;
        }

        public Criteria andField6IsNotNull() {
            addCriterion("field6 is not null");
            return (Criteria) this;
        }

        public Criteria andField6EqualTo(Long value) {
            addCriterion("field6 =", value, "field6");
            return (Criteria) this;
        }

        public Criteria andField6NotEqualTo(Long value) {
            addCriterion("field6 <>", value, "field6");
            return (Criteria) this;
        }

        public Criteria andField6GreaterThan(Long value) {
            addCriterion("field6 >", value, "field6");
            return (Criteria) this;
        }

        public Criteria andField6GreaterThanOrEqualTo(Long value) {
            addCriterion("field6 >=", value, "field6");
            return (Criteria) this;
        }

        public Criteria andField6LessThan(Long value) {
            addCriterion("field6 <", value, "field6");
            return (Criteria) this;
        }

        public Criteria andField6LessThanOrEqualTo(Long value) {
            addCriterion("field6 <=", value, "field6");
            return (Criteria) this;
        }

        public Criteria andField6In(List<Long> values) {
            addCriterion("field6 in", values, "field6");
            return (Criteria) this;
        }

        public Criteria andField6NotIn(List<Long> values) {
            addCriterion("field6 not in", values, "field6");
            return (Criteria) this;
        }

        public Criteria andField6Between(Long value1, Long value2) {
            addCriterion("field6 between", value1, value2, "field6");
            return (Criteria) this;
        }

        public Criteria andField6NotBetween(Long value1, Long value2) {
            addCriterion("field6 not between", value1, value2, "field6");
            return (Criteria) this;
        }

        public Criteria andField7IsNull() {
            addCriterion("field7 is null");
            return (Criteria) this;
        }

        public Criteria andField7IsNotNull() {
            addCriterion("field7 is not null");
            return (Criteria) this;
        }

        public Criteria andField7EqualTo(BigDecimal value) {
            addCriterion("field7 =", value, "field7");
            return (Criteria) this;
        }

        public Criteria andField7NotEqualTo(BigDecimal value) {
            addCriterion("field7 <>", value, "field7");
            return (Criteria) this;
        }

        public Criteria andField7GreaterThan(BigDecimal value) {
            addCriterion("field7 >", value, "field7");
            return (Criteria) this;
        }

        public Criteria andField7GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("field7 >=", value, "field7");
            return (Criteria) this;
        }

        public Criteria andField7LessThan(BigDecimal value) {
            addCriterion("field7 <", value, "field7");
            return (Criteria) this;
        }

        public Criteria andField7LessThanOrEqualTo(BigDecimal value) {
            addCriterion("field7 <=", value, "field7");
            return (Criteria) this;
        }

        public Criteria andField7In(List<BigDecimal> values) {
            addCriterion("field7 in", values, "field7");
            return (Criteria) this;
        }

        public Criteria andField7NotIn(List<BigDecimal> values) {
            addCriterion("field7 not in", values, "field7");
            return (Criteria) this;
        }

        public Criteria andField7Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("field7 between", value1, value2, "field7");
            return (Criteria) this;
        }

        public Criteria andField7NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("field7 not between", value1, value2, "field7");
            return (Criteria) this;
        }

        public Criteria andField8IsNull() {
            addCriterion("field8 is null");
            return (Criteria) this;
        }

        public Criteria andField8IsNotNull() {
            addCriterion("field8 is not null");
            return (Criteria) this;
        }

        public Criteria andField8EqualTo(Short value) {
            addCriterion("field8 =", value, "field8");
            return (Criteria) this;
        }

        public Criteria andField8NotEqualTo(Short value) {
            addCriterion("field8 <>", value, "field8");
            return (Criteria) this;
        }

        public Criteria andField8GreaterThan(Short value) {
            addCriterion("field8 >", value, "field8");
            return (Criteria) this;
        }

        public Criteria andField8GreaterThanOrEqualTo(Short value) {
            addCriterion("field8 >=", value, "field8");
            return (Criteria) this;
        }

        public Criteria andField8LessThan(Short value) {
            addCriterion("field8 <", value, "field8");
            return (Criteria) this;
        }

        public Criteria andField8LessThanOrEqualTo(Short value) {
            addCriterion("field8 <=", value, "field8");
            return (Criteria) this;
        }

        public Criteria andField8In(List<Short> values) {
            addCriterion("field8 in", values, "field8");
            return (Criteria) this;
        }

        public Criteria andField8NotIn(List<Short> values) {
            addCriterion("field8 not in", values, "field8");
            return (Criteria) this;
        }

        public Criteria andField8Between(Short value1, Short value2) {
            addCriterion("field8 between", value1, value2, "field8");
            return (Criteria) this;
        }

        public Criteria andField8NotBetween(Short value1, Short value2) {
            addCriterion("field8 not between", value1, value2, "field8");
            return (Criteria) this;
        }

        public Criteria andField9IsNull() {
            addCriterion("field9 is null");
            return (Criteria) this;
        }

        public Criteria andField9IsNotNull() {
            addCriterion("field9 is not null");
            return (Criteria) this;
        }

        public Criteria andField9EqualTo(Integer value) {
            addCriterion("field9 =", value, "field9");
            return (Criteria) this;
        }

        public Criteria andField9NotEqualTo(Integer value) {
            addCriterion("field9 <>", value, "field9");
            return (Criteria) this;
        }

        public Criteria andField9GreaterThan(Integer value) {
            addCriterion("field9 >", value, "field9");
            return (Criteria) this;
        }

        public Criteria andField9GreaterThanOrEqualTo(Integer value) {
            addCriterion("field9 >=", value, "field9");
            return (Criteria) this;
        }

        public Criteria andField9LessThan(Integer value) {
            addCriterion("field9 <", value, "field9");
            return (Criteria) this;
        }

        public Criteria andField9LessThanOrEqualTo(Integer value) {
            addCriterion("field9 <=", value, "field9");
            return (Criteria) this;
        }

        public Criteria andField9In(List<Integer> values) {
            addCriterion("field9 in", values, "field9");
            return (Criteria) this;
        }

        public Criteria andField9NotIn(List<Integer> values) {
            addCriterion("field9 not in", values, "field9");
            return (Criteria) this;
        }

        public Criteria andField9Between(Integer value1, Integer value2) {
            addCriterion("field9 between", value1, value2, "field9");
            return (Criteria) this;
        }

        public Criteria andField9NotBetween(Integer value1, Integer value2) {
            addCriterion("field9 not between", value1, value2, "field9");
            return (Criteria) this;
        }

        public Criteria andField10IsNull() {
            addCriterion("field10 is null");
            return (Criteria) this;
        }

        public Criteria andField10IsNotNull() {
            addCriterion("field10 is not null");
            return (Criteria) this;
        }

        public Criteria andField10EqualTo(Long value) {
            addCriterion("field10 =", value, "field10");
            return (Criteria) this;
        }

        public Criteria andField10NotEqualTo(Long value) {
            addCriterion("field10 <>", value, "field10");
            return (Criteria) this;
        }

        public Criteria andField10GreaterThan(Long value) {
            addCriterion("field10 >", value, "field10");
            return (Criteria) this;
        }

        public Criteria andField10GreaterThanOrEqualTo(Long value) {
            addCriterion("field10 >=", value, "field10");
            return (Criteria) this;
        }

        public Criteria andField10LessThan(Long value) {
            addCriterion("field10 <", value, "field10");
            return (Criteria) this;
        }

        public Criteria andField10LessThanOrEqualTo(Long value) {
            addCriterion("field10 <=", value, "field10");
            return (Criteria) this;
        }

        public Criteria andField10In(List<Long> values) {
            addCriterion("field10 in", values, "field10");
            return (Criteria) this;
        }

        public Criteria andField10NotIn(List<Long> values) {
            addCriterion("field10 not in", values, "field10");
            return (Criteria) this;
        }

        public Criteria andField10Between(Long value1, Long value2) {
            addCriterion("field10 between", value1, value2, "field10");
            return (Criteria) this;
        }

        public Criteria andField10NotBetween(Long value1, Long value2) {
            addCriterion("field10 not between", value1, value2, "field10");
            return (Criteria) this;
        }

        public Criteria andField11IsNull() {
            addCriterion("field11 is null");
            return (Criteria) this;
        }

        public Criteria andField11IsNotNull() {
            addCriterion("field11 is not null");
            return (Criteria) this;
        }

        public Criteria andField11EqualTo(Double value) {
            addCriterion("field11 =", value, "field11");
            return (Criteria) this;
        }

        public Criteria andField11NotEqualTo(Double value) {
            addCriterion("field11 <>", value, "field11");
            return (Criteria) this;
        }

        public Criteria andField11GreaterThan(Double value) {
            addCriterion("field11 >", value, "field11");
            return (Criteria) this;
        }

        public Criteria andField11GreaterThanOrEqualTo(Double value) {
            addCriterion("field11 >=", value, "field11");
            return (Criteria) this;
        }

        public Criteria andField11LessThan(Double value) {
            addCriterion("field11 <", value, "field11");
            return (Criteria) this;
        }

        public Criteria andField11LessThanOrEqualTo(Double value) {
            addCriterion("field11 <=", value, "field11");
            return (Criteria) this;
        }

        public Criteria andField11In(List<Double> values) {
            addCriterion("field11 in", values, "field11");
            return (Criteria) this;
        }

        public Criteria andField11NotIn(List<Double> values) {
            addCriterion("field11 not in", values, "field11");
            return (Criteria) this;
        }

        public Criteria andField11Between(Double value1, Double value2) {
            addCriterion("field11 between", value1, value2, "field11");
            return (Criteria) this;
        }

        public Criteria andField11NotBetween(Double value1, Double value2) {
            addCriterion("field11 not between", value1, value2, "field11");
            return (Criteria) this;
        }

        public Criteria andField12IsNull() {
            addCriterion("field12 is null");
            return (Criteria) this;
        }

        public Criteria andField12IsNotNull() {
            addCriterion("field12 is not null");
            return (Criteria) this;
        }

        public Criteria andField12EqualTo(String value) {
            addCriterion("field12 =", value, "field12");
            return (Criteria) this;
        }

        public Criteria andField12NotEqualTo(String value) {
            addCriterion("field12 <>", value, "field12");
            return (Criteria) this;
        }

        public Criteria andField12GreaterThan(String value) {
            addCriterion("field12 >", value, "field12");
            return (Criteria) this;
        }

        public Criteria andField12GreaterThanOrEqualTo(String value) {
            addCriterion("field12 >=", value, "field12");
            return (Criteria) this;
        }

        public Criteria andField12LessThan(String value) {
            addCriterion("field12 <", value, "field12");
            return (Criteria) this;
        }

        public Criteria andField12LessThanOrEqualTo(String value) {
            addCriterion("field12 <=", value, "field12");
            return (Criteria) this;
        }

        public Criteria andField12Like(String value) {
            addCriterion("field12 like", value, "field12");
            return (Criteria) this;
        }

        public Criteria andField12NotLike(String value) {
            addCriterion("field12 not like", value, "field12");
            return (Criteria) this;
        }

        public Criteria andField12In(List<String> values) {
            addCriterion("field12 in", values, "field12");
            return (Criteria) this;
        }

        public Criteria andField12NotIn(List<String> values) {
            addCriterion("field12 not in", values, "field12");
            return (Criteria) this;
        }

        public Criteria andField12Between(String value1, String value2) {
            addCriterion("field12 between", value1, value2, "field12");
            return (Criteria) this;
        }

        public Criteria andField12NotBetween(String value1, String value2) {
            addCriterion("field12 not between", value1, value2, "field12");
            return (Criteria) this;
        }

        public Criteria andField13IsNull() {
            addCriterion("field13 is null");
            return (Criteria) this;
        }

        public Criteria andField13IsNotNull() {
            addCriterion("field13 is not null");
            return (Criteria) this;
        }

        public Criteria andField13EqualTo(String value) {
            addCriterion("field13 =", value, "field13");
            return (Criteria) this;
        }

        public Criteria andField13NotEqualTo(String value) {
            addCriterion("field13 <>", value, "field13");
            return (Criteria) this;
        }

        public Criteria andField13GreaterThan(String value) {
            addCriterion("field13 >", value, "field13");
            return (Criteria) this;
        }

        public Criteria andField13GreaterThanOrEqualTo(String value) {
            addCriterion("field13 >=", value, "field13");
            return (Criteria) this;
        }

        public Criteria andField13LessThan(String value) {
            addCriterion("field13 <", value, "field13");
            return (Criteria) this;
        }

        public Criteria andField13LessThanOrEqualTo(String value) {
            addCriterion("field13 <=", value, "field13");
            return (Criteria) this;
        }

        public Criteria andField13Like(String value) {
            addCriterion("field13 like", value, "field13");
            return (Criteria) this;
        }

        public Criteria andField13NotLike(String value) {
            addCriterion("field13 not like", value, "field13");
            return (Criteria) this;
        }

        public Criteria andField13In(List<String> values) {
            addCriterion("field13 in", values, "field13");
            return (Criteria) this;
        }

        public Criteria andField13NotIn(List<String> values) {
            addCriterion("field13 not in", values, "field13");
            return (Criteria) this;
        }

        public Criteria andField13Between(String value1, String value2) {
            addCriterion("field13 between", value1, value2, "field13");
            return (Criteria) this;
        }

        public Criteria andField13NotBetween(String value1, String value2) {
            addCriterion("field13 not between", value1, value2, "field13");
            return (Criteria) this;
        }

        public Criteria andField14IsNull() {
            addCriterion("field14 is null");
            return (Criteria) this;
        }

        public Criteria andField14IsNotNull() {
            addCriterion("field14 is not null");
            return (Criteria) this;
        }

        public Criteria andField14EqualTo(String value) {
            addCriterion("field14 =", value, "field14");
            return (Criteria) this;
        }

        public Criteria andField14NotEqualTo(String value) {
            addCriterion("field14 <>", value, "field14");
            return (Criteria) this;
        }

        public Criteria andField14GreaterThan(String value) {
            addCriterion("field14 >", value, "field14");
            return (Criteria) this;
        }

        public Criteria andField14GreaterThanOrEqualTo(String value) {
            addCriterion("field14 >=", value, "field14");
            return (Criteria) this;
        }

        public Criteria andField14LessThan(String value) {
            addCriterion("field14 <", value, "field14");
            return (Criteria) this;
        }

        public Criteria andField14LessThanOrEqualTo(String value) {
            addCriterion("field14 <=", value, "field14");
            return (Criteria) this;
        }

        public Criteria andField14Like(String value) {
            addCriterion("field14 like", value, "field14");
            return (Criteria) this;
        }

        public Criteria andField14NotLike(String value) {
            addCriterion("field14 not like", value, "field14");
            return (Criteria) this;
        }

        public Criteria andField14In(List<String> values) {
            addCriterion("field14 in", values, "field14");
            return (Criteria) this;
        }

        public Criteria andField14NotIn(List<String> values) {
            addCriterion("field14 not in", values, "field14");
            return (Criteria) this;
        }

        public Criteria andField14Between(String value1, String value2) {
            addCriterion("field14 between", value1, value2, "field14");
            return (Criteria) this;
        }

        public Criteria andField14NotBetween(String value1, String value2) {
            addCriterion("field14 not between", value1, value2, "field14");
            return (Criteria) this;
        }

        public Criteria andField16IsNull() {
            addCriterion("field16 is null");
            return (Criteria) this;
        }

        public Criteria andField16IsNotNull() {
            addCriterion("field16 is not null");
            return (Criteria) this;
        }

        public Criteria andField16EqualTo(LocalDateTime value) {
            addCriterion("field16 =", value, "field16");
            return (Criteria) this;
        }

        public Criteria andField16NotEqualTo(LocalDateTime value) {
            addCriterion("field16 <>", value, "field16");
            return (Criteria) this;
        }

        public Criteria andField16GreaterThan(LocalDateTime value) {
            addCriterion("field16 >", value, "field16");
            return (Criteria) this;
        }

        public Criteria andField16GreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("field16 >=", value, "field16");
            return (Criteria) this;
        }

        public Criteria andField16LessThan(LocalDateTime value) {
            addCriterion("field16 <", value, "field16");
            return (Criteria) this;
        }

        public Criteria andField16LessThanOrEqualTo(LocalDateTime value) {
            addCriterion("field16 <=", value, "field16");
            return (Criteria) this;
        }

        public Criteria andField16In(List<LocalDateTime> values) {
            addCriterion("field16 in", values, "field16");
            return (Criteria) this;
        }

        public Criteria andField16NotIn(List<LocalDateTime> values) {
            addCriterion("field16 not in", values, "field16");
            return (Criteria) this;
        }

        public Criteria andField16Between(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("field16 between", value1, value2, "field16");
            return (Criteria) this;
        }

        public Criteria andField16NotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("field16 not between", value1, value2, "field16");
            return (Criteria) this;
        }

        public Criteria andField17IsNull() {
            addCriterion("field17 is null");
            return (Criteria) this;
        }

        public Criteria andField17IsNotNull() {
            addCriterion("field17 is not null");
            return (Criteria) this;
        }

        public Criteria andField17EqualTo(LocalDateTime value) {
            addCriterion("field17 =", value, "field17");
            return (Criteria) this;
        }

        public Criteria andField17NotEqualTo(LocalDateTime value) {
            addCriterion("field17 <>", value, "field17");
            return (Criteria) this;
        }

        public Criteria andField17GreaterThan(LocalDateTime value) {
            addCriterion("field17 >", value, "field17");
            return (Criteria) this;
        }

        public Criteria andField17GreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("field17 >=", value, "field17");
            return (Criteria) this;
        }

        public Criteria andField17LessThan(LocalDateTime value) {
            addCriterion("field17 <", value, "field17");
            return (Criteria) this;
        }

        public Criteria andField17LessThanOrEqualTo(LocalDateTime value) {
            addCriterion("field17 <=", value, "field17");
            return (Criteria) this;
        }

        public Criteria andField17In(List<LocalDateTime> values) {
            addCriterion("field17 in", values, "field17");
            return (Criteria) this;
        }

        public Criteria andField17NotIn(List<LocalDateTime> values) {
            addCriterion("field17 not in", values, "field17");
            return (Criteria) this;
        }

        public Criteria andField17Between(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("field17 between", value1, value2, "field17");
            return (Criteria) this;
        }

        public Criteria andField17NotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("field17 not between", value1, value2, "field17");
            return (Criteria) this;
        }

        public Criteria andField18IsNull() {
            addCriterion("field18 is null");
            return (Criteria) this;
        }

        public Criteria andField18IsNotNull() {
            addCriterion("field18 is not null");
            return (Criteria) this;
        }

        public Criteria andField18EqualTo(LocalTime value) {
            addCriterion("field18 =", value, "field18");
            return (Criteria) this;
        }

        public Criteria andField18NotEqualTo(LocalTime value) {
            addCriterion("field18 <>", value, "field18");
            return (Criteria) this;
        }

        public Criteria andField18GreaterThan(LocalTime value) {
            addCriterion("field18 >", value, "field18");
            return (Criteria) this;
        }

        public Criteria andField18GreaterThanOrEqualTo(LocalTime value) {
            addCriterion("field18 >=", value, "field18");
            return (Criteria) this;
        }

        public Criteria andField18LessThan(LocalTime value) {
            addCriterion("field18 <", value, "field18");
            return (Criteria) this;
        }

        public Criteria andField18LessThanOrEqualTo(LocalTime value) {
            addCriterion("field18 <=", value, "field18");
            return (Criteria) this;
        }

        public Criteria andField18In(List<LocalTime> values) {
            addCriterion("field18 in", values, "field18");
            return (Criteria) this;
        }

        public Criteria andField18NotIn(List<LocalTime> values) {
            addCriterion("field18 not in", values, "field18");
            return (Criteria) this;
        }

        public Criteria andField18Between(LocalTime value1, LocalTime value2) {
            addCriterion("field18 between", value1, value2, "field18");
            return (Criteria) this;
        }

        public Criteria andField18NotBetween(LocalTime value1, LocalTime value2) {
            addCriterion("field18 not between", value1, value2, "field18");
            return (Criteria) this;
        }

        public Criteria andField19IsNull() {
            addCriterion("field19 is null");
            return (Criteria) this;
        }

        public Criteria andField19IsNotNull() {
            addCriterion("field19 is not null");
            return (Criteria) this;
        }

        public Criteria andField19EqualTo(LocalTime value) {
            addCriterion("field19 =", value, "field19");
            return (Criteria) this;
        }

        public Criteria andField19NotEqualTo(LocalTime value) {
            addCriterion("field19 <>", value, "field19");
            return (Criteria) this;
        }

        public Criteria andField19GreaterThan(LocalTime value) {
            addCriterion("field19 >", value, "field19");
            return (Criteria) this;
        }

        public Criteria andField19GreaterThanOrEqualTo(LocalTime value) {
            addCriterion("field19 >=", value, "field19");
            return (Criteria) this;
        }

        public Criteria andField19LessThan(LocalTime value) {
            addCriterion("field19 <", value, "field19");
            return (Criteria) this;
        }

        public Criteria andField19LessThanOrEqualTo(LocalTime value) {
            addCriterion("field19 <=", value, "field19");
            return (Criteria) this;
        }

        public Criteria andField19In(List<LocalTime> values) {
            addCriterion("field19 in", values, "field19");
            return (Criteria) this;
        }

        public Criteria andField19NotIn(List<LocalTime> values) {
            addCriterion("field19 not in", values, "field19");
            return (Criteria) this;
        }

        public Criteria andField19Between(LocalTime value1, LocalTime value2) {
            addCriterion("field19 between", value1, value2, "field19");
            return (Criteria) this;
        }

        public Criteria andField19NotBetween(LocalTime value1, LocalTime value2) {
            addCriterion("field19 not between", value1, value2, "field19");
            return (Criteria) this;
        }

        public Criteria andField20IsNull() {
            addCriterion("field20 is null");
            return (Criteria) this;
        }

        public Criteria andField20IsNotNull() {
            addCriterion("field20 is not null");
            return (Criteria) this;
        }

        public Criteria andField20EqualTo(LocalDate value) {
            addCriterion("field20 =", value, "field20");
            return (Criteria) this;
        }

        public Criteria andField20NotEqualTo(LocalDate value) {
            addCriterion("field20 <>", value, "field20");
            return (Criteria) this;
        }

        public Criteria andField20GreaterThan(LocalDate value) {
            addCriterion("field20 >", value, "field20");
            return (Criteria) this;
        }

        public Criteria andField20GreaterThanOrEqualTo(LocalDate value) {
            addCriterion("field20 >=", value, "field20");
            return (Criteria) this;
        }

        public Criteria andField20LessThan(LocalDate value) {
            addCriterion("field20 <", value, "field20");
            return (Criteria) this;
        }

        public Criteria andField20LessThanOrEqualTo(LocalDate value) {
            addCriterion("field20 <=", value, "field20");
            return (Criteria) this;
        }

        public Criteria andField20In(List<LocalDate> values) {
            addCriterion("field20 in", values, "field20");
            return (Criteria) this;
        }

        public Criteria andField20NotIn(List<LocalDate> values) {
            addCriterion("field20 not in", values, "field20");
            return (Criteria) this;
        }

        public Criteria andField20Between(LocalDate value1, LocalDate value2) {
            addCriterion("field20 between", value1, value2, "field20");
            return (Criteria) this;
        }

        public Criteria andField20NotBetween(LocalDate value1, LocalDate value2) {
            addCriterion("field20 not between", value1, value2, "field20");
            return (Criteria) this;
        }

        public Criteria andField21IsNull() {
            addCriterion("field21 is null");
            return (Criteria) this;
        }

        public Criteria andField21IsNotNull() {
            addCriterion("field21 is not null");
            return (Criteria) this;
        }

        public Criteria andField21EqualTo(Object value) {
            addCriterion("field21 =", value, "field21");
            return (Criteria) this;
        }

        public Criteria andField21NotEqualTo(Object value) {
            addCriterion("field21 <>", value, "field21");
            return (Criteria) this;
        }

        public Criteria andField21GreaterThan(Object value) {
            addCriterion("field21 >", value, "field21");
            return (Criteria) this;
        }

        public Criteria andField21GreaterThanOrEqualTo(Object value) {
            addCriterion("field21 >=", value, "field21");
            return (Criteria) this;
        }

        public Criteria andField21LessThan(Object value) {
            addCriterion("field21 <", value, "field21");
            return (Criteria) this;
        }

        public Criteria andField21LessThanOrEqualTo(Object value) {
            addCriterion("field21 <=", value, "field21");
            return (Criteria) this;
        }

        public Criteria andField21In(List<Object> values) {
            addCriterion("field21 in", values, "field21");
            return (Criteria) this;
        }

        public Criteria andField21NotIn(List<Object> values) {
            addCriterion("field21 not in", values, "field21");
            return (Criteria) this;
        }

        public Criteria andField21Between(Object value1, Object value2) {
            addCriterion("field21 between", value1, value2, "field21");
            return (Criteria) this;
        }

        public Criteria andField21NotBetween(Object value1, Object value2) {
            addCriterion("field21 not between", value1, value2, "field21");
            return (Criteria) this;
        }

        public Criteria andField22IsNull() {
            addCriterion("field22 is null");
            return (Criteria) this;
        }

        public Criteria andField22IsNotNull() {
            addCriterion("field22 is not null");
            return (Criteria) this;
        }

        public Criteria andField22EqualTo(Boolean value) {
            addCriterion("field22 =", value, "field22");
            return (Criteria) this;
        }

        public Criteria andField22NotEqualTo(Boolean value) {
            addCriterion("field22 <>", value, "field22");
            return (Criteria) this;
        }

        public Criteria andField22GreaterThan(Boolean value) {
            addCriterion("field22 >", value, "field22");
            return (Criteria) this;
        }

        public Criteria andField22GreaterThanOrEqualTo(Boolean value) {
            addCriterion("field22 >=", value, "field22");
            return (Criteria) this;
        }

        public Criteria andField22LessThan(Boolean value) {
            addCriterion("field22 <", value, "field22");
            return (Criteria) this;
        }

        public Criteria andField22LessThanOrEqualTo(Boolean value) {
            addCriterion("field22 <=", value, "field22");
            return (Criteria) this;
        }

        public Criteria andField22In(List<Boolean> values) {
            addCriterion("field22 in", values, "field22");
            return (Criteria) this;
        }

        public Criteria andField22NotIn(List<Boolean> values) {
            addCriterion("field22 not in", values, "field22");
            return (Criteria) this;
        }

        public Criteria andField22Between(Boolean value1, Boolean value2) {
            addCriterion("field22 between", value1, value2, "field22");
            return (Criteria) this;
        }

        public Criteria andField22NotBetween(Boolean value1, Boolean value2) {
            addCriterion("field22 not between", value1, value2, "field22");
            return (Criteria) this;
        }

        public Criteria andField23IsNull() {
            addCriterion("field23 is null");
            return (Criteria) this;
        }

        public Criteria andField23IsNotNull() {
            addCriterion("field23 is not null");
            return (Criteria) this;
        }

        public Criteria andField23EqualTo(Object value) {
            addCriterion("field23 =", value, "field23");
            return (Criteria) this;
        }

        public Criteria andField23NotEqualTo(Object value) {
            addCriterion("field23 <>", value, "field23");
            return (Criteria) this;
        }

        public Criteria andField23GreaterThan(Object value) {
            addCriterion("field23 >", value, "field23");
            return (Criteria) this;
        }

        public Criteria andField23GreaterThanOrEqualTo(Object value) {
            addCriterion("field23 >=", value, "field23");
            return (Criteria) this;
        }

        public Criteria andField23LessThan(Object value) {
            addCriterion("field23 <", value, "field23");
            return (Criteria) this;
        }

        public Criteria andField23LessThanOrEqualTo(Object value) {
            addCriterion("field23 <=", value, "field23");
            return (Criteria) this;
        }

        public Criteria andField23In(List<Object> values) {
            addCriterion("field23 in", values, "field23");
            return (Criteria) this;
        }

        public Criteria andField23NotIn(List<Object> values) {
            addCriterion("field23 not in", values, "field23");
            return (Criteria) this;
        }

        public Criteria andField23Between(Object value1, Object value2) {
            addCriterion("field23 between", value1, value2, "field23");
            return (Criteria) this;
        }

        public Criteria andField23NotBetween(Object value1, Object value2) {
            addCriterion("field23 not between", value1, value2, "field23");
            return (Criteria) this;
        }

        public Criteria andField12LikeInsensitive(String value) {
            addCriterion("upper(field12) like", value.toUpperCase(), "field12");
            return (Criteria) this;
        }

        public Criteria andField13LikeInsensitive(String value) {
            addCriterion("upper(field13) like", value.toUpperCase(), "field13");
            return (Criteria) this;
        }

        public Criteria andField14LikeInsensitive(String value) {
            addCriterion("upper(field14) like", value.toUpperCase(), "field14");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table nokey_with_blob
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table nokey_with_blob
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}