package com.example.mbgexample.domain.model;

import java.io.Serializable;
import java.time.LocalDateTime;

/**
 * Database Table Remarks:
 *   通常テーブル
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table normal_table
 */
public class NormalTable implements Serializable {
    /**
     * Database Column Remarks:
     *   ユーザid
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column normal_table.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     * Database Column Remarks:
     *   ステータス
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column normal_table.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * Database Column Remarks:
     *   バージョン
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column normal_table.version
     *
     * @mbg.generated
     */
    private Long version;

    /**
     * Database Column Remarks:
     *   作成者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column normal_table.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     * Database Column Remarks:
     *   作成日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column normal_table.created_date
     *
     * @mbg.generated
     */
    private LocalDateTime createdDate;

    /**
     * Database Column Remarks:
     *   最終更新者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column normal_table.last_modified_by
     *
     * @mbg.generated
     */
    private String lastModifiedBy;

    /**
     * Database Column Remarks:
     *   最終更新日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column normal_table.last_modified_date
     *
     * @mbg.generated
     */
    private LocalDateTime lastModifiedDate;

    /**
     * Database Column Remarks:
     *   パスワード
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column normal_table.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     * Database Column Remarks:
     *   名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column normal_table.first_name
     *
     * @mbg.generated
     */
    private String firstName;

    /**
     * Database Column Remarks:
     *   姓
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column normal_table.last_name
     *
     * @mbg.generated
     */
    private String lastName;

    /**
     * Database Column Remarks:
     *   メールアドレス
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column normal_table.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     * Database Column Remarks:
     *   所属部門
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column normal_table.department
     *
     * @mbg.generated
     */
    private String department;

    /**
     * Database Column Remarks:
     *   url
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column normal_table.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     * Database Column Remarks:
     *   プロフィール
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column normal_table.profile
     *
     * @mbg.generated
     */
    private String profile;

    /**
     * Database Column Remarks:
     *   イメージファイルUUID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column normal_table.image_uuid
     *
     * @mbg.generated
     */
    private String imageUuid;

    /**
     * Database Column Remarks:
     *   ログイン許可ipアドレス
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column normal_table.allowed_ip
     *
     * @mbg.generated
     */
    private String allowedIp;

    /**
     * Database Column Remarks:
     *   api key
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column normal_table.api_key
     *
     * @mbg.generated
     */
    private String apiKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table normal_table
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column normal_table.username
     *
     * @return the value of normal_table.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column normal_table.username
     *
     * @param username the value for normal_table.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column normal_table.status
     *
     * @return the value of normal_table.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column normal_table.status
     *
     * @param status the value for normal_table.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column normal_table.version
     *
     * @return the value of normal_table.version
     *
     * @mbg.generated
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column normal_table.version
     *
     * @param version the value for normal_table.version
     *
     * @mbg.generated
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column normal_table.created_by
     *
     * @return the value of normal_table.created_by
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column normal_table.created_by
     *
     * @param createdBy the value for normal_table.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column normal_table.created_date
     *
     * @return the value of normal_table.created_date
     *
     * @mbg.generated
     */
    public LocalDateTime getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column normal_table.created_date
     *
     * @param createdDate the value for normal_table.created_date
     *
     * @mbg.generated
     */
    public void setCreatedDate(LocalDateTime createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column normal_table.last_modified_by
     *
     * @return the value of normal_table.last_modified_by
     *
     * @mbg.generated
     */
    public String getLastModifiedBy() {
        return lastModifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column normal_table.last_modified_by
     *
     * @param lastModifiedBy the value for normal_table.last_modified_by
     *
     * @mbg.generated
     */
    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column normal_table.last_modified_date
     *
     * @return the value of normal_table.last_modified_date
     *
     * @mbg.generated
     */
    public LocalDateTime getLastModifiedDate() {
        return lastModifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column normal_table.last_modified_date
     *
     * @param lastModifiedDate the value for normal_table.last_modified_date
     *
     * @mbg.generated
     */
    public void setLastModifiedDate(LocalDateTime lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column normal_table.password
     *
     * @return the value of normal_table.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column normal_table.password
     *
     * @param password the value for normal_table.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column normal_table.first_name
     *
     * @return the value of normal_table.first_name
     *
     * @mbg.generated
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column normal_table.first_name
     *
     * @param firstName the value for normal_table.first_name
     *
     * @mbg.generated
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column normal_table.last_name
     *
     * @return the value of normal_table.last_name
     *
     * @mbg.generated
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column normal_table.last_name
     *
     * @param lastName the value for normal_table.last_name
     *
     * @mbg.generated
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column normal_table.email
     *
     * @return the value of normal_table.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column normal_table.email
     *
     * @param email the value for normal_table.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column normal_table.department
     *
     * @return the value of normal_table.department
     *
     * @mbg.generated
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column normal_table.department
     *
     * @param department the value for normal_table.department
     *
     * @mbg.generated
     */
    public void setDepartment(String department) {
        this.department = department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column normal_table.url
     *
     * @return the value of normal_table.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column normal_table.url
     *
     * @param url the value for normal_table.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column normal_table.profile
     *
     * @return the value of normal_table.profile
     *
     * @mbg.generated
     */
    public String getProfile() {
        return profile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column normal_table.profile
     *
     * @param profile the value for normal_table.profile
     *
     * @mbg.generated
     */
    public void setProfile(String profile) {
        this.profile = profile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column normal_table.image_uuid
     *
     * @return the value of normal_table.image_uuid
     *
     * @mbg.generated
     */
    public String getImageUuid() {
        return imageUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column normal_table.image_uuid
     *
     * @param imageUuid the value for normal_table.image_uuid
     *
     * @mbg.generated
     */
    public void setImageUuid(String imageUuid) {
        this.imageUuid = imageUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column normal_table.allowed_ip
     *
     * @return the value of normal_table.allowed_ip
     *
     * @mbg.generated
     */
    public String getAllowedIp() {
        return allowedIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column normal_table.allowed_ip
     *
     * @param allowedIp the value for normal_table.allowed_ip
     *
     * @mbg.generated
     */
    public void setAllowedIp(String allowedIp) {
        this.allowedIp = allowedIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column normal_table.api_key
     *
     * @return the value of normal_table.api_key
     *
     * @mbg.generated
     */
    public String getApiKey() {
        return apiKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column normal_table.api_key
     *
     * @param apiKey the value for normal_table.api_key
     *
     * @mbg.generated
     */
    public void setApiKey(String apiKey) {
        this.apiKey = apiKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table normal_table
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        NormalTable other = (NormalTable) that;
        return (this.getUsername() == null ? other.getUsername() == null : this.getUsername().equals(other.getUsername()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getVersion() == null ? other.getVersion() == null : this.getVersion().equals(other.getVersion()))
            && (this.getCreatedBy() == null ? other.getCreatedBy() == null : this.getCreatedBy().equals(other.getCreatedBy()))
            && (this.getCreatedDate() == null ? other.getCreatedDate() == null : this.getCreatedDate().equals(other.getCreatedDate()))
            && (this.getLastModifiedBy() == null ? other.getLastModifiedBy() == null : this.getLastModifiedBy().equals(other.getLastModifiedBy()))
            && (this.getLastModifiedDate() == null ? other.getLastModifiedDate() == null : this.getLastModifiedDate().equals(other.getLastModifiedDate()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
            && (this.getFirstName() == null ? other.getFirstName() == null : this.getFirstName().equals(other.getFirstName()))
            && (this.getLastName() == null ? other.getLastName() == null : this.getLastName().equals(other.getLastName()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getDepartment() == null ? other.getDepartment() == null : this.getDepartment().equals(other.getDepartment()))
            && (this.getUrl() == null ? other.getUrl() == null : this.getUrl().equals(other.getUrl()))
            && (this.getProfile() == null ? other.getProfile() == null : this.getProfile().equals(other.getProfile()))
            && (this.getImageUuid() == null ? other.getImageUuid() == null : this.getImageUuid().equals(other.getImageUuid()))
            && (this.getAllowedIp() == null ? other.getAllowedIp() == null : this.getAllowedIp().equals(other.getAllowedIp()))
            && (this.getApiKey() == null ? other.getApiKey() == null : this.getApiKey().equals(other.getApiKey()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table normal_table
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getVersion() == null) ? 0 : getVersion().hashCode());
        result = prime * result + ((getCreatedBy() == null) ? 0 : getCreatedBy().hashCode());
        result = prime * result + ((getCreatedDate() == null) ? 0 : getCreatedDate().hashCode());
        result = prime * result + ((getLastModifiedBy() == null) ? 0 : getLastModifiedBy().hashCode());
        result = prime * result + ((getLastModifiedDate() == null) ? 0 : getLastModifiedDate().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getFirstName() == null) ? 0 : getFirstName().hashCode());
        result = prime * result + ((getLastName() == null) ? 0 : getLastName().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getDepartment() == null) ? 0 : getDepartment().hashCode());
        result = prime * result + ((getUrl() == null) ? 0 : getUrl().hashCode());
        result = prime * result + ((getProfile() == null) ? 0 : getProfile().hashCode());
        result = prime * result + ((getImageUuid() == null) ? 0 : getImageUuid().hashCode());
        result = prime * result + ((getAllowedIp() == null) ? 0 : getAllowedIp().hashCode());
        result = prime * result + ((getApiKey() == null) ? 0 : getApiKey().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table normal_table
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", username=").append(username);
        sb.append(", status=").append(status);
        sb.append(", version=").append(version);
        sb.append(", createdBy=").append(createdBy);
        sb.append(", createdDate=").append(createdDate);
        sb.append(", lastModifiedBy=").append(lastModifiedBy);
        sb.append(", lastModifiedDate=").append(lastModifiedDate);
        sb.append(", password=").append(password);
        sb.append(", firstName=").append(firstName);
        sb.append(", lastName=").append(lastName);
        sb.append(", email=").append(email);
        sb.append(", department=").append(department);
        sb.append(", url=").append(url);
        sb.append(", profile=").append(profile);
        sb.append(", imageUuid=").append(imageUuid);
        sb.append(", allowedIp=").append(allowedIp);
        sb.append(", apiKey=").append(apiKey);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}