package com.example.mbgexample.application.mapper;

import com.example.mbgexample.domain.model.ComplexkeyTable;
import com.example.mbgexample.domain.model.ComplexkeyTableExample;
import com.example.mbgexample.domain.model.ComplexkeyTableKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface ComplexkeyTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complexkey_table
     *
     * @mbg.generated
     */
    long countByExample(ComplexkeyTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complexkey_table
     *
     * @mbg.generated
     */
    int deleteByExample(ComplexkeyTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complexkey_table
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(ComplexkeyTableKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complexkey_table
     *
     * @mbg.generated
     */
    int insert(ComplexkeyTable row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complexkey_table
     *
     * @mbg.generated
     */
    int insertSelective(ComplexkeyTable row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complexkey_table
     *
     * @mbg.generated
     */
    List<ComplexkeyTable> selectByExampleWithRowbounds(ComplexkeyTableExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complexkey_table
     *
     * @mbg.generated
     */
    List<ComplexkeyTable> selectByExample(ComplexkeyTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complexkey_table
     *
     * @mbg.generated
     */
    ComplexkeyTable selectByPrimaryKey(ComplexkeyTableKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complexkey_table
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") ComplexkeyTable row, @Param("example") ComplexkeyTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complexkey_table
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") ComplexkeyTable row, @Param("example") ComplexkeyTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complexkey_table
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ComplexkeyTable row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complexkey_table
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ComplexkeyTable row);
}