package com.example.mbgexample.application.mapper;

import com.example.mbgexample.domain.model.NokeyWithBlob;
import com.example.mbgexample.domain.model.NokeyWithBlobExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface NokeyWithBlobMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nokey_with_blob
     *
     * @mbg.generated
     */
    long countByExample(NokeyWithBlobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nokey_with_blob
     *
     * @mbg.generated
     */
    int deleteByExample(NokeyWithBlobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nokey_with_blob
     *
     * @mbg.generated
     */
    int insert(NokeyWithBlob row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nokey_with_blob
     *
     * @mbg.generated
     */
    int insertSelective(NokeyWithBlob row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nokey_with_blob
     *
     * @mbg.generated
     */
    List<NokeyWithBlob> selectByExampleWithBLOBsWithRowbounds(NokeyWithBlobExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nokey_with_blob
     *
     * @mbg.generated
     */
    List<NokeyWithBlob> selectByExampleWithBLOBs(NokeyWithBlobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nokey_with_blob
     *
     * @mbg.generated
     */
    List<NokeyWithBlob> selectByExampleWithRowbounds(NokeyWithBlobExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nokey_with_blob
     *
     * @mbg.generated
     */
    List<NokeyWithBlob> selectByExample(NokeyWithBlobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nokey_with_blob
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") NokeyWithBlob row, @Param("example") NokeyWithBlobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nokey_with_blob
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("row") NokeyWithBlob row, @Param("example") NokeyWithBlobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nokey_with_blob
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") NokeyWithBlob row, @Param("example") NokeyWithBlobExample example);
}