package com.example.mbgexample.application.mapper;

import com.example.mbgexample.domain.model.NormalTable;
import com.example.mbgexample.domain.model.NormalTableExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface NormalTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table normal_table
     *
     * @mbg.generated
     */
    long countByExample(NormalTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table normal_table
     *
     * @mbg.generated
     */
    int deleteByExample(NormalTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table normal_table
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table normal_table
     *
     * @mbg.generated
     */
    int insert(NormalTable row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table normal_table
     *
     * @mbg.generated
     */
    int insertSelective(NormalTable row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table normal_table
     *
     * @mbg.generated
     */
    List<NormalTable> selectByExampleWithRowbounds(NormalTableExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table normal_table
     *
     * @mbg.generated
     */
    List<NormalTable> selectByExample(NormalTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table normal_table
     *
     * @mbg.generated
     */
    NormalTable selectByPrimaryKey(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table normal_table
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") NormalTable row, @Param("example") NormalTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table normal_table
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") NormalTable row, @Param("example") NormalTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table normal_table
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(NormalTable row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table normal_table
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(NormalTable row);
}